spring.application.name=energy-community-usage-service

server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:postgresql://localhost:5432/energy_community
spring.datasource.username=energy_user
spring.datasource.password=energy_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
